# This file contains values from Cookiecutter

default_context:
  project_name: "test-template"
  project_description: "Awesome `test-template` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "test-template"
  license: "MIT"
  version: "0.1.0"
  github_name: "shyam1311"
  email: "vn.shyamkumar@gmail.com"
